#define _GNU_SOURCE 1
#include <assert.h>
#include <stdarg.h>
#include <stdint.h>
#include <semaphore.h>
#include <nvidia.h>
// Include the backend to exercise its actual internal copy/export paths.
#include "../src/direct/direct-export-buf.c"
#undef _GNU_SOURCE
#define cacheBackingImageFdStat auditVaCacheBackingImageFdStat
#include "../src/vabackend.c"
#undef cacheBackingImageFdStat
#if NVD_TEST_VP9
#include "../src/vp9.c"
#endif

static int rmFailure;
void *__real_dlopen(const char *file, int mode);
void *__wrap_dlopen(const char *file, int mode);
void *__wrap_dlopen(const char *file, int mode) {
    // Keep this a CPU-only test even on hosts with the NVIDIA libraries.
    if (file != NULL && (strstr(file, "libcuda") != NULL || strstr(file, "libnvcuvid") != NULL))
        return NULL;
    return __real_dlopen(file, mode);
}
int __wrap_ioctl(int fd, unsigned long request, ...);
int __wrap_ioctl(int fd, unsigned long request, ...) {
    va_list args;
    va_start(args, request);
    NVOS54_PARAMETERS *control = va_arg(args, NVOS54_PARAMETERS *);
    va_end(args);
    assert(control->cmd == NV0000_CTRL_CMD_GPU_GET_UUID_FROM_GPU_ID);
    if (rmFailure == 1) return -1;
    control->status = rmFailure == 2 ? 1 : 0;
    NV0000_CTRL_GPU_GET_UUID_FROM_GPU_ID_PARAMS *uuid = (void *)(uintptr_t) control->params;
    memset(uuid->gpuUuid, 0x5a, 16);
    return 0;
}

static int copies, syncs, events, copyFailure, eventFailure, syncFailure;
static CUresult CUDAAPI mockCopy(const CUDA_MEMCPY2D *copy, CUstream stream) {
    copies++;
    assert(syncs == 0);
    return copies == copyFailure ? CUDA_ERROR_UNKNOWN : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockSync(CUstream stream) {
    syncs++;
    return syncFailure ? CUDA_ERROR_UNKNOWN : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockEvent(CUevent event, CUstream stream) {
    events++;
    assert(copies == 2 && syncs == 0);
    return eventFailure ? CUDA_ERROR_UNKNOWN : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockMemset(CUdeviceptr ptr, unsigned char value, size_t size, CUstream stream) {
    return CUDA_SUCCESS;
}

static void testUuid(void) {
    NVDriverContext ctx = {0};
    uint8_t uuid[16];
    for (rmFailure = 0; rmFailure < 3; rmFailure++) {
        memset(uuid, 0xcc, sizeof(uuid));
        assert(get_device_uuid(&ctx, uuid) == (rmFailure == 0));
        for (unsigned i = 0; i < 16; i++) assert(uuid[i] == (rmFailure == 0 ? 0x5a : 0xcc));
    }
}

static CUresult CUDAAPI mockDeviceCount(int *count) {
    *count = 2;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockUuid(CUuuid *uuid, CUdevice device) {
    memset(uuid->bytes, device == 1 ? 0x5a : 0xbb, sizeof(uuid->bytes));
    return CUDA_SUCCESS;
}
static void testGpuIdentity(void) {
    CudaFunctions cuda = {.cuDeviceGetCount = mockDeviceCount, .cuDeviceGetUuid = mockUuid};
    NVDriver drv = {.cu = &cuda, .cudaGpuId = 0};
    rmFailure = 0;
    assert(findGPUIndexFromFd(&drv));
    assert(drv.cudaGpuId == 1);
    rmFailure = 1;
    assert(!findGPUIndexFromFd(&drv));
}

#if NVD_TEST_VP9
static void testVp9(void) {
    // 64x64 black keyframe, generated by ffmpeg/libvpx-vp9; IVF headers removed.
    uint8_t frame[] = {0x82,0x49,0x83,0x42,0x00,0x03,0xf0,0x03,0xf6,0x00,0x38,
        0x24,0x1c,0x18,0x4a,0x00,0x00,0x30,0x60,0x00,0x00,0x67,0x3f,0xff,
        0xff,0x56,0x45,0x64,0xee,0xcc,0x00};
    NVSurface surface = {0};
    NVContext ctx = {.renderTarget = &surface};
    NVContext other = {.renderTarget = &surface};
    CUVIDPICPARAMS params = {0};
    pthread_mutex_init(&surface.mutex, NULL);
    parseExtraInfo(&ctx, frame, sizeof(frame), &params);
    assert(!ctx.inputValidationFailed);
    VP9Context *vp9 = ctx.codecData;
    GstVp9Parser *parser = vp9->parser;
    uint8_t invalidHeader[] = {0, 0}; // Invalid VP9 frame marker.
    parseExtraInfo(&ctx, invalidHeader, sizeof(invalidHeader), &params);
    assert(ctx.inputValidationFailed);
    ctx.inputValidationFailed = false;
    parseExtraInfo(&ctx, frame, sizeof(frame), &params);
    assert(!ctx.inputValidationFailed && vp9->parser == parser);
    parseExtraInfo(&other, frame, sizeof(frame), &params);
    assert(!other.inputValidationFailed);
    assert(((VP9Context *)other.codecData)->parser != parser);
    destroyVP9Context(&ctx);
    destroyVP9Context(&other);
    free(ctx.codecData);
    free(other.codecData);
    pthread_mutex_destroy(&surface.mutex);
}
#endif

static void testLayout(void) {
    NVDriverContext ctx = {0};
    NVDriverImage images[3] = {0};
    const NVFormatInfo *fmt = &formatsInfo[NV_FORMAT_NV12];
    uint32_t size = 123;
    assert(!calculate_unified_image_layout(&ctx, images, 65534, 43690, 1, 2, fmt->plane, true, &size));
    assert(size == 0);
    const uint32_t dimensions[][2] = {{1,1}, {63,65}, {128,128}, {256,144}, {1920,1080}, {3840,2160}, {7680,4320}};
    for (unsigned f = NV_FORMAT_NV12; f <= NV_FORMAT_ARGB; f++) {
        fmt = &formatsInfo[f];
        if (fmt->numPlanes == 0) continue;
        for (unsigned d = 0; d < ARRAY_SIZE(dimensions); d++) {
            for (unsigned shared = 0; shared < 2; shared++) {
                assert(calculate_unified_image_layout(&ctx, images, dimensions[d][0], dimensions[d][1],
                    fmt->bppc, fmt->numPlanes, fmt->plane, shared, &size));
                for (unsigned p = 0; p < fmt->numPlanes; p++) {
                    assert((uint64_t) images[p].offset + images[p].memorySize <= size);
                    assert(images[p].pitch >= (uint64_t) images[p].width * fmt->bppc * fmt->plane[p].channelCount);
                    assert(images[p].offset % 65536 == 0);
                }
            }
        }
    }
    fmt = &formatsInfo[NV_FORMAT_NV12];
    assert(!calculate_unified_image_layout(&ctx, images, 0, 1, 1, 2, fmt->plane, true, &size));
    assert(!calculate_unified_image_layout(&ctx, images, UINT32_MAX, UINT32_MAX, 2, 2, fmt->plane, true, &size));
    assert(!alloc_image(&ctx, UINT32_MAX, UINT32_MAX, 4, 16, 0, images));
}

static void closeDescriptor(VADRMPRIMESurfaceDescriptor *desc) {
    for (unsigned i = 0; i < desc->num_objects; i++) close(desc->objects[i].fd);
}

static void testDescriptor(void) {
    NVDriver drv = {0};
    FILE *a = tmpfile(), *b = tmpfile();
    assert(a != NULL && b != NULL);
    BackingImage img = {.format = NV_FORMAT_NV12, .fourcc = VA_FOURCC_NV12,
        .numObjects = 2, .numPlanes = 2, .fds = {fileno(a), fileno(b)},
        .objectSize = {8192, 16384}, .planeObjectIndex = {1, 0},
        .strides = {128, 128}, .mods = {DRM_FORMAT_MOD_LINEAR, DRM_FORMAT_MOD_LINEAR}};
    NVSurface surface = {.width = 128, .height = 128, .backingImage = &img};
    VADRMPRIMESurfaceDescriptor desc;
    assert(direct_fillExportDescriptor(&drv, &surface, &desc));
    assert(desc.num_objects == 2 && desc.layers[0].object_index[0] == 1 && desc.layers[1].object_index[0] == 0);
    assert(desc.objects[0].size == 8192 && desc.objects[1].size == 16384);
    struct stat original, exported;
    assert(fstat(fileno(b), &original) == 0 && fstat(desc.objects[1].fd, &exported) == 0);
    assert(original.st_ino == exported.st_ino && original.st_dev == exported.st_dev);
    assert(fcntl(desc.objects[0].fd, F_GETFD) & FD_CLOEXEC);
    closeDescriptor(&desc);
    img.numObjects = 1;
    img.planeObjectIndex[0] = 0;
    img.objectSize[0] = 24576;
    img.offsets[1] = 16384;
    assert(direct_fillExportDescriptor(&drv, &surface, &desc));
    assert(desc.num_objects == 1 && desc.layers[1].offset[0] == 16384);
    closeDescriptor(&desc);
    const uint32_t rgb[][2] = {
        {VA_FOURCC_ARGB, DRM_FORMAT_BGRA8888}, {VA_FOURCC_XRGB, DRM_FORMAT_BGRX8888},
        {VA_FOURCC_ABGR, DRM_FORMAT_RGBA8888}, {VA_FOURCC_XBGR, DRM_FORMAT_RGBX8888},
        {VA_FOURCC_RGBA, DRM_FORMAT_ABGR8888}, {VA_FOURCC_RGBX, DRM_FORMAT_XBGR8888},
        {VA_FOURCC_BGRA, DRM_FORMAT_ARGB8888}, {VA_FOURCC_BGRX, DRM_FORMAT_XRGB8888}};
    img.format = NV_FORMAT_ARGB;
    img.numPlanes = 1;
    for (unsigned i = 0; i < ARRAY_SIZE(rgb); i++) {
        img.fourcc = rgb[i][0];
        assert(direct_fillExportDescriptor(&drv, &surface, &desc));
        assert(desc.fourcc == rgb[i][0] && desc.layers[0].drm_format == rgb[i][1]);
        closeDescriptor(&desc);
    }
    img.objectSize[0] = UINT64_C(1) << 32;
    assert(!direct_fillExportDescriptor(&drv, &surface, &desc));
    assert(desc.num_objects == 0);
    fclose(a);
    fclose(b);
}

static void testCopyFailures(void) {
    CudaFunctions cuda = {.cuMemcpy2DAsync = mockCopy, .cuStreamSynchronize = mockSync,
        .cuEventRecord = mockEvent, .cuMemsetD8Async = mockMemset};
    NVDriver drv = {.cu = &cuda};
    BackingImage img = {.format = NV_FORMAT_NV12, .width = 4096, .height = 4096};
    NVSurface surface = {.width = 128, .height = 128, .backingImage = &img};
    for (unsigned scenario = 0; scenario < 5; scenario++) {
        copies = syncs = events = 0;
        copyFailure = scenario == 1 ? 1 : scenario == 2 ? 2 : 0;
        eventFailure = scenario == 3;
        syncFailure = scenario == 4;
        atomic_store(&drv.cudaWorkUnsafe, false);
        assert(copyFrameToSurface(&drv, 1, &surface, 128, (CUstream)1, (CUevent)1) == (scenario == 0));
        assert(syncs == 1);
        assert(atomic_load(&drv.cudaWorkUnsafe) == (scenario == 4));
    }
    pthread_mutex_init(&drv.securityClearMutex, NULL);
    drv.securityClearStream = (CUstream)1;
    drv.securityClearBuffer = 1;
    drv.securityClearBufferSize = 8 * 1024 * 1024;
    copies = syncs = events = 0;
    copyFailure = 2;
    syncFailure = 0;
    atomic_store(&drv.cudaWorkUnsafe, false);
    assert(!clearBackingImagePlaneGpu(&drv, &img, 0));
    assert(copies == 2 && syncs == 1 && !atomic_load(&drv.cudaWorkUnsafe));
    copies = syncs = 0;
    syncFailure = 1;
    assert(!clearBackingImage(&drv, &img)); // No CPU fallback after failed drain.
    assert(atomic_load(&drv.cudaWorkUnsafe));
    // A quarantined image must not be freed, even on allocation cleanup.
    destroyBackingImage(&drv, &img);
    pthread_mutex_destroy(&drv.securityClearMutex);
}

static int pushFailure, unmaps, decoderDestroys;
static NVSurface *workerSurface;
static CUresult CUDAAPI mockPush(CUcontext context) {
    return pushFailure ? CUDA_ERROR_UNKNOWN : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockPop(CUcontext *context) { return CUDA_SUCCESS; }
static CUresult CUDAAPI mockCreateStream(CUstream *stream, unsigned flags) {
    *stream = (CUstream)1;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockCreateEvent(CUevent *event, unsigned flags) {
    *event = (CUevent)1;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockDestroyStream(CUstream stream) {
    assert(syncs > 0);
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockDestroyEvent(CUevent event) { return CUDA_SUCCESS; }
static CUresult CUDAAPI mockMap(CUvideodecoder decoder, int picture,
                                CUdeviceptr *ptr, unsigned *pitch, CUVIDPROCPARAMS *params) {
    *ptr = 1;
    *pitch = 128;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockUnmap(CUvideodecoder decoder, CUdeviceptr ptr) {
    assert(syncs > 0 && !syncFailure && workerSurface->resolving);
    assert(workerSurface->backingImage->resolving);
    unmaps++;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockDestroyDecoder(CUvideodecoder decoder) {
    assert(syncs > 0 && !syncFailure);
    decoderDestroys++;
    return CUDA_SUCCESS;
}

static void testWorkerFailures(void) {
    CudaFunctions cuda = {.cuMemcpy2DAsync = mockCopy, .cuStreamSynchronize = mockSync,
        .cuEventRecord = mockEvent, .cuCtxPushCurrent = mockPush, .cuCtxPopCurrent = mockPop,
        .cuStreamCreate = mockCreateStream, .cuEventCreate = mockCreateEvent,
        .cuStreamDestroy = mockDestroyStream, .cuEventDestroy = mockDestroyEvent};
    CuvidFunctions cuvid = {.cuvidMapVideoFrame = mockMap,
        .cuvidUnmapVideoFrame = mockUnmap, .cuvidDestroyDecoder = mockDestroyDecoder};
    cu = &cuda;
    cv = &cuvid;
    for (unsigned scenario = 0; scenario < 5; scenario++) {
        copies = syncs = events = unmaps = decoderDestroys = 0;
        copyFailure = scenario == 1 ? 2 : 0;
        eventFailure = scenario == 2;
        syncFailure = scenario == 3;
        pushFailure = scenario == 4;
        NVDriver drv = {.cu = &cuda, .backend = &DIRECT_BACKEND};
        BackingImage img = {.format = NV_FORMAT_NV12};
        assert(initBackingImageSync(&img));
        NVSurface surface = {.width = 128, .height = 128, .backingImage = &img,
            .resolving = 1, .submittedGeneration = 1};
        pthread_mutex_init(&surface.mutex, NULL);
        pthread_cond_init(&surface.cond, NULL);
        workerSurface = &surface;
        NVContext ctx = {.drv = &drv, .decoder = (CUvideodecoder)1};
        assert(resolveQueueInit(&ctx.resolveQueue));
        ResolveJob *job = calloc(1, sizeof(*job));
        assert(job != NULL);
        job->surface = &surface;
        job->decoder = ctx.decoder;
        job->generation = 1;
        assert(resolveQueuePush(&ctx.resolveQueue, job));
        resolveQueueShutdown(&ctx.resolveQueue);
        resolveSurfaces(&ctx);
        assert(!surface.resolving && !img.resolving);
        assert(surface.decodeFailed == (scenario != 0));
        assert(unmaps == (scenario < 3 ? 1 : 0));
        assert(decoderDestroys == (scenario < 3 ? 1 : 0));
        assert(atomic_load(&drv.cudaWorkUnsafe) == (scenario == 3));
        resolveQueueDestroy(&ctx.resolveQueue);
        pthread_cond_destroy(&surface.cond);
        pthread_mutex_destroy(&surface.mutex);
        pthread_cond_destroy(&img.cond);
        pthread_mutex_destroy(&img.mutex);
    }
    cu = NULL;
    cv = NULL;
}

typedef struct {
    VADriverContextP driver;
    VAContextID context;
    VAStatus status;
    sem_t returned;
} SubmitTest;

static CUresult CUDAAPI mockDecode(CUvideodecoder decoder, CUVIDPICPARAMS *picture) {
    return CUDA_SUCCESS;
}

static void *submitTestPicture(void *opaque) {
    SubmitTest *submit = opaque;
    submit->status = nvEndPicture(submit->driver, submit->context);
    assert(sem_post(&submit->returned) == 0);
    return NULL;
}

static void testSharedSurfaceSubmission(void) {
    CudaFunctions cuda = {.cuCtxPushCurrent = mockPush, .cuCtxPopCurrent = mockPop};
    CuvidFunctions cuvid = {.cuvidDecodePicture = mockDecode};
    cu = &cuda;
    cv = &cuvid;
    pushFailure = 0;
    // Exercise the public EndPicture/Export entrypoints. Keep the worker's job
    // pending so completion cannot accidentally depend on a fast GPU/copy.
    for (unsigned kind = 0; kind < 3; kind++) {
        pthread_rwlock_t lifetime;
        assert(pthread_rwlock_init(&lifetime, NULL) == 0);
        NVDriver drv = {.cu = &cuda, .backend = &DIRECT_BACKEND,
                        .objectLifetimeLock = &lifetime};
        nvdObjectTableInit(&drv.objects);
        assert(pthread_mutex_init(&drv.objectCreationMutex, NULL) == 0);
        struct VADriverContext driver = {.pDriverData = &drv};
        Object contextObject = allocateObject(&drv, OBJECT_TYPE_CONTEXT, sizeof(NVContext));
        Object surfaceObject = allocateObject(&drv, OBJECT_TYPE_SURFACE, sizeof(NVSurface));
        assert(contextObject != NULL && surfaceObject != NULL);
        NVContext *ctx = contextObject->obj;
        NVSurface *surface = surfaceObject->obj;
        ctx->drv = &drv;
        ctx->id = contextObject->id;
        ctx->decoder = (CUvideodecoder)1;
        assert(pthread_mutex_init(&ctx->pictureMutex, NULL) == 0);
        assert(pthread_mutex_init(&ctx->surfaceCreationMutex, NULL) == 0);
        assert(resolveQueueInit(&ctx->resolveQueue));
        assert(pthread_mutex_init(&surface->mutex, NULL) == 0);
        assert(pthread_cond_init(&surface->cond, NULL) == 0);
        FILE *fd = tmpfile();
        assert(fd != NULL);
        BackingImage img = {.format = NV_FORMAT_NV12, .fourcc = VA_FOURCC_NV12,
            .numObjects = 1, .numPlanes = 2, .fds = {fileno(fd)},
            .objectSize = {24576}, .offsets = {0, 16384}, .strides = {128, 128},
            .isExternalBuffer = kind == 2};
        surface->width = surface->height = 128;
        surface->backingImage = &img;
        if (kind == 1) {
            // Export once, before decoding, then keep the handle across frames.
            VADRMPRIMESurfaceDescriptor desc;
            assert(nvExportSurfaceHandle(&driver, surfaceObject->id,
                VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2,
                VA_EXPORT_SURFACE_READ_ONLY | VA_EXPORT_SURFACE_SEPARATE_LAYERS,
                &desc) == VA_STATUS_SUCCESS);
            assert(surface->exported);
            closeDescriptor(&desc);
        }
        for (unsigned frame = 0; frame < 2; frame++) {
            ctx->renderTarget = ctx->displayTarget = surface;
            ctx->pictureState = NVD_PICTURE_BUILDING;
            const uint8_t byte = 0;
            assert(appendBuffer(&ctx->bitstreamBuffer, &byte, 1));
            setSurfaceResolving(surface, true);
            SubmitTest submit = {.driver = &driver, .context = contextObject->id};
            assert(sem_init(&submit.returned, 0, 0) == 0);
            pthread_t thread;
            assert(pthread_create(&thread, NULL, submitTestPicture, &submit) == 0);
            ResolveJob *job = NULL;
            assert(resolveQueuePop(&ctx->resolveQueue, (void **)&job));
            assert(job->surface == surface && job->generation == frame + 1);
            if (kind == 0) {
                // A private surface must still submit asynchronously.
                assert(pthread_join(thread, NULL) == 0);
                assert(submit.status == VA_STATUS_SUCCESS && surface->resolving);
            } else {
                struct timespec deadline;
                assert(clock_gettime(CLOCK_REALTIME, &deadline) == 0);
                deadline.tv_nsec += 50000000;
                if (deadline.tv_nsec >= 1000000000) {
                    deadline.tv_sec++;
                    deadline.tv_nsec -= 1000000000;
                }
                int result;
                do { result = sem_timedwait(&submit.returned, &deadline); }
                while (result != 0 && errno == EINTR);
                assert(result == -1 && errno == ETIMEDOUT);
            }
            if (frame == 0) setSurfaceResolving(surface, false);
            else failSurfaceResolve(surface, VA_STATUS_ERROR_DECODING_ERROR);
            free(job);
            if (kind != 0) {
                assert(pthread_join(thread, NULL) == 0);
                assert(submit.status == (frame == 0 ? VA_STATUS_SUCCESS : VA_STATUS_ERROR_DECODING_ERROR));
                assert(!surface->resolving);
            }
            assert(ctx->pictureState == NVD_PICTURE_IDLE);
            sem_destroy(&submit.returned);
        }
        // A failed resolve must not publish an old or partially copied frame.
        // A subsequent successful generation can be exported normally.
        VADRMPRIMESurfaceDescriptor failedDescriptor = {0};
        assert(nvExportSurfaceHandle(&driver, surfaceObject->id,
            VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2,
            VA_EXPORT_SURFACE_READ_ONLY | VA_EXPORT_SURFACE_SEPARATE_LAYERS,
            &failedDescriptor) == VA_STATUS_ERROR_DECODING_ERROR);
        assert(failedDescriptor.num_objects == 0);
        assert(surface->exported == (kind == 1));
        setSurfaceResolving(surface, true);
        setSurfaceResolving(surface, false);
        assert(nvExportSurfaceHandle(&driver, surfaceObject->id,
            VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2,
            VA_EXPORT_SURFACE_READ_ONLY | VA_EXPORT_SURFACE_SEPARATE_LAYERS,
            &failedDescriptor) == VA_STATUS_SUCCESS);
        assert(surface->exported);
        closeDescriptor(&failedDescriptor);
        free(ctx->bitstreamBuffer.buf);
        resolveQueueDestroy(&ctx->resolveQueue);
        pthread_mutex_destroy(&ctx->pictureMutex);
        pthread_mutex_destroy(&ctx->surfaceCreationMutex);
        pthread_cond_destroy(&surface->cond);
        pthread_mutex_destroy(&surface->mutex);
        deleteObject(&drv, surfaceObject->id);
        deleteObject(&drv, contextObject->id);
        nvdObjectTableDestroy(&drv.objects);
        pthread_mutex_destroy(&drv.objectCreationMutex);
        pthread_rwlock_destroy(&lifetime);
        fclose(fd);
    }
    cu = NULL;
    cv = NULL;
}


static void testStatsAccounting(void) {
    NVDriver drv = {.statsEnabled = true};
    BackingImage owner = {.totalSize = 4096};
    BackingImage borrower1 = {.totalSize = 4096, .borrowedBackingImage = &owner};
    BackingImage borrower2 = {.totalSize = 4096, .borrowedBackingImage = &owner};
    BackingImage external = {.totalSize = 8192, .isExternalBuffer = true};
    nvStatsBackingImageCreated(&drv, &owner, true);
    nvStatsBackingImageCreated(&drv, &borrower1, true);
    nvStatsBackingImageCreated(&drv, &borrower2, true);
    nvStatsBackingImageCreated(&drv, &external, true);
    assert(atomic_load(&drv.stats[NV_STAT_UNIQUE_OWNED_BACKING_BYTES]) == 4096);
    assert(atomic_load(&drv.stats[NV_STAT_BORROWED_VIEW_BYTES]) == 8192);
    assert(atomic_load(&drv.stats[NV_STAT_EXTERNAL_IMPORT_BYTES]) == 8192);
    nvStatsBackingImageCreated(&drv, &owner, true); // Idempotent.
    nvStatsBackingImageSetActive(&drv, &owner, false);
    assert(atomic_load(&drv.stats[NV_STAT_UNIQUE_OWNED_BACKING_BYTES]) == 4096);
    nvStatsBackingImageDestroyed(&drv, &borrower1);
    nvStatsBackingImageDestroyed(&drv, &borrower1);
    assert(atomic_load(&drv.stats[NV_STAT_BORROWED_VIEW_BYTES]) == 4096);
    nvStatsBackingImageDestroyed(&drv, &borrower2);
    nvStatsBackingImageDestroyed(&drv, &external);
    nvStatsBackingImageDestroyed(&drv, &owner);
    assert(atomic_load(&drv.stats[NV_STAT_OWNED_GPU_BYTES]) == 0);
    assert(atomic_load(&drv.stats[NV_STAT_BORROWED_VIEW_BYTES]) == 0);
    assert(atomic_load(&drv.stats[NV_STAT_EXTERNAL_IMPORT_BYTES]) == 0);

    drv.bufferPoolMaxBytes = 8192;
    assert(pthread_mutex_init(&drv.bufferPoolMutex, NULL) == 0);
    drv.bufferPoolMutexInitialized = true;
    NVBuffer buffer = {0};
    assert(allocateBufferMemory(&drv, &buffer, 17));
    assert(atomic_load(&drv.stats[NV_STAT_BUFFER_LIVE_REQUESTED_BYTES]) == 17);
    assert(atomic_load(&drv.stats[NV_STAT_TRACKED_HOST_BYTES]) == buffer.capacity);
    const size_t capacity = buffer.capacity;
    releaseBufferMemory(&drv, &buffer);
    assert(atomic_load(&drv.stats[NV_STAT_BUFFER_LIVE_REQUESTED_BYTES]) == 0);
    assert(atomic_load(&drv.stats[NV_STAT_BUFFER_LIVE_CAPACITY_BYTES]) == 0);
    assert(atomic_load(&drv.stats[NV_STAT_TRACKED_HOST_BYTES]) == capacity);
    destroyBufferPool(&drv);
    assert(atomic_load(&drv.stats[NV_STAT_TRACKED_HOST_BYTES]) == 0);
    pthread_mutex_destroy(&drv.bufferPoolMutex);

    NVContext ctx = {.drv = &drv};
    assert(reserveBuffer(&ctx.bitstreamBuffer, 1024));
    nvStatsContextHostBuffers(&ctx);
    assert(atomic_load(&drv.stats[NV_STAT_CONTEXT_HOST_BUFFER_BYTES]) == ctx.bitstreamBuffer.allocated);
    freeAppendableBuffer(&ctx.bitstreamBuffer);
    nvStatsContextHostBuffers(&ctx);
    assert(atomic_load(&drv.stats[NV_STAT_TRACKED_HOST_BYTES]) == 0);
}

static void testTimingHistograms(void) {
    NVDriver drv = {0};
    assert(nvStatsTimestamp(&drv) == 0);
    nvStatsObserve(&drv, NV_TIMING_MAP, 1001);
    assert(atomic_load(&drv.timings[NV_TIMING_MAP].buckets[1]) == 0);
    drv.statsEnabled = true;
    nvStatsObserve(&drv, NV_TIMING_MAP, 0);
    nvStatsObserve(&drv, NV_TIMING_MAP, 1000);
    nvStatsObserve(&drv, NV_TIMING_MAP, 1001);
    nvStatsObserve(&drv, NV_TIMING_MAP, UINT64_MAX);
    assert(atomic_load(&drv.timings[NV_TIMING_MAP].buckets[0]) == 2);
    assert(atomic_load(&drv.timings[NV_TIMING_MAP].buckets[1]) == 1);
    assert(atomic_load(&drv.timings[NV_TIMING_MAP].buckets[NV_TIMING_BUCKETS - 1]) == 1);
    NVContext ctx = {.drv = &drv};
    const uint64_t start = nvStatsTimestamp(&drv);
    assert(start > 0);
    nvStatsRecordContext(&ctx, NV_TIMING_QUEUE_RESIDENCE, true, start);
    uint64_t shared = 0, private = 0;
    for (unsigned i = 0; i < NV_TIMING_BUCKETS; i++) {
        shared += atomic_load(&ctx.timings[1][NV_TIMING_QUEUE_RESIDENCE].buckets[i]);
        private += atomic_load(&ctx.timings[0][NV_TIMING_QUEUE_RESIDENCE].buckets[i]);
    }
    assert(shared == 1 && private == 0);
}

int main(void) {
    testStatsAccounting();
    testTimingHistograms();
    testUuid();
    testGpuIdentity();
    testLayout();
    testDescriptor();
    testCopyFailures();
    testWorkerFailures();
    testSharedSurfaceSubmission();
#if NVD_TEST_VP9
    testVp9();
#endif
    return 0;
}
