#define _GNU_SOURCE 1
#include <assert.h>
#include <stdarg.h>
#include <stdint.h>
#include <nvidia.h>
// Include the backend to exercise its actual internal copy/export paths.
#include "../src/direct/direct-export-buf.c"
#undef _GNU_SOURCE
#define cacheBackingImageFdStat auditVaCacheBackingImageFdStat
#include "../src/vabackend.c"
#undef cacheBackingImageFdStat
#if NVD_TEST_VP9
#include "../src/vp9.c"
#endif

static int rmFailure;
void *__real_dlopen(const char *file, int mode);
void *__wrap_dlopen(const char *file, int mode);
void *__wrap_dlopen(const char *file, int mode) {
    // Keep this a CPU-only test even on hosts with the NVIDIA libraries.
    if (file != NULL && (strstr(file, "libcuda") != NULL || strstr(file, "libnvcuvid") != NULL))
        return NULL;
    return __real_dlopen(file, mode);
}
int __wrap_ioctl(int fd, unsigned long request, ...);
int __wrap_ioctl(int fd, unsigned long request, ...) {
    va_list args;
    va_start(args, request);
    NVOS54_PARAMETERS *control = va_arg(args, NVOS54_PARAMETERS *);
    va_end(args);
    assert(control->cmd == NV0000_CTRL_CMD_GPU_GET_UUID_FROM_GPU_ID);
    if (rmFailure == 1) return -1;
    control->status = rmFailure == 2 ? 1 : 0;
    NV0000_CTRL_GPU_GET_UUID_FROM_GPU_ID_PARAMS *uuid = (void *)(uintptr_t) control->params;
    memset(uuid->gpuUuid, 0x5a, 16);
    return 0;
}

static int copies, syncs, events, copyFailure, eventFailure, syncFailure;
static CUresult CUDAAPI mockCopy(const CUDA_MEMCPY2D *copy, CUstream stream) {
    copies++;
    assert(syncs == 0);
    return copies == copyFailure ? CUDA_ERROR_INVALID_VALUE : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockSync(CUstream stream) {
    syncs++;
    return syncFailure ? CUDA_ERROR_UNKNOWN : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockEvent(CUevent event, CUstream stream) {
    events++;
    assert(copies == 2 && syncs == 0);
    return eventFailure ? CUDA_ERROR_INVALID_VALUE : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockMemset(CUdeviceptr ptr, unsigned char value, size_t size, CUstream stream) {
    return CUDA_SUCCESS;
}

static void testUuid(void) {
    NVDriverContext ctx = {0};
    uint8_t uuid[16];
    for (rmFailure = 0; rmFailure < 3; rmFailure++) {
        memset(uuid, 0xcc, sizeof(uuid));
        assert(get_device_uuid(&ctx, uuid) == (rmFailure == 0));
        for (unsigned i = 0; i < 16; i++) assert(uuid[i] == (rmFailure == 0 ? 0x5a : 0xcc));
    }
}

static CUresult CUDAAPI mockDeviceCount(int *count) {
    *count = 2;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockUuid(CUuuid *uuid, CUdevice device) {
    memset(uuid->bytes, device == 1 ? 0x5a : 0xbb, sizeof(uuid->bytes));
    return CUDA_SUCCESS;
}
static void testGpuIdentity(void) {
    CudaFunctions cuda = {.cuDeviceGetCount = mockDeviceCount, .cuDeviceGetUuid = mockUuid};
    NVDriver drv = {.cu = &cuda, .cudaGpuId = 0};
    rmFailure = 0;
    assert(findGPUIndexFromFd(&drv));
    assert(drv.cudaGpuId == 1);
    rmFailure = 1;
    assert(!findGPUIndexFromFd(&drv));
}

#if NVD_TEST_VP9
static void testVp9(void) {
    // 64x64 black keyframe, generated by ffmpeg/libvpx-vp9; IVF headers removed.
    uint8_t frame[] = {0x82,0x49,0x83,0x42,0x00,0x03,0xf0,0x03,0xf6,0x00,0x38,
        0x24,0x1c,0x18,0x4a,0x00,0x00,0x30,0x60,0x00,0x00,0x67,0x3f,0xff,
        0xff,0x56,0x45,0x64,0xee,0xcc,0x00};
    NVSurface surface = {0};
    NVContext ctx = {.renderTarget = &surface};
    NVContext other = {.renderTarget = &surface};
    CUVIDPICPARAMS params = {0};
    pthread_mutex_init(&surface.mutex, NULL);
    parseExtraInfo(&ctx, frame, sizeof(frame), &params);
    assert(!ctx.inputValidationFailed);
    VP9Context *vp9 = ctx.codecData;
    GstVp9Parser *parser = vp9->parser;
    uint8_t invalidHeader[] = {0, 0}; // Invalid VP9 frame marker.
    parseExtraInfo(&ctx, invalidHeader, sizeof(invalidHeader), &params);
    assert(ctx.inputValidationFailed);
    ctx.inputValidationFailed = false;
    parseExtraInfo(&ctx, frame, sizeof(frame), &params);
    assert(!ctx.inputValidationFailed && vp9->parser == parser);
    parseExtraInfo(&other, frame, sizeof(frame), &params);
    assert(!other.inputValidationFailed);
    assert(((VP9Context *)other.codecData)->parser != parser);
    destroyVP9Context(&ctx);
    destroyVP9Context(&other);
    free(ctx.codecData);
    free(other.codecData);
    pthread_mutex_destroy(&surface.mutex);
}
#endif

static void testLayout(void) {
    NVDriverContext ctx = {0};
    NVDriverImage images[3] = {0};
    const NVFormatInfo *fmt = &formatsInfo[NV_FORMAT_NV12];
    uint32_t size = 123;
    assert(!calculate_unified_image_layout(&ctx, images, 65534, 43690, 1, 2, fmt->plane, true, &size));
    assert(size == 0);
    const uint32_t dimensions[][2] = {{1,1}, {63,65}, {128,128}, {256,144}, {1920,1080}, {3840,2160}, {7680,4320}};
    for (unsigned f = NV_FORMAT_NV12; f <= NV_FORMAT_ARGB; f++) {
        fmt = &formatsInfo[f];
        if (fmt->numPlanes == 0) continue;
        for (unsigned d = 0; d < ARRAY_SIZE(dimensions); d++) {
            for (unsigned shared = 0; shared < 2; shared++) {
                assert(calculate_unified_image_layout(&ctx, images, dimensions[d][0], dimensions[d][1],
                    fmt->bppc, fmt->numPlanes, fmt->plane, shared, &size));
                for (unsigned p = 0; p < fmt->numPlanes; p++) {
                    assert((uint64_t) images[p].offset + images[p].memorySize <= size);
                    assert(images[p].pitch >= (uint64_t) images[p].width * fmt->bppc * fmt->plane[p].channelCount);
                    assert(images[p].offset % 65536 == 0);
                }
            }
        }
    }
    fmt = &formatsInfo[NV_FORMAT_NV12];
    assert(!calculate_unified_image_layout(&ctx, images, 0, 1, 1, 2, fmt->plane, true, &size));
    assert(!calculate_unified_image_layout(&ctx, images, UINT32_MAX, UINT32_MAX, 2, 2, fmt->plane, true, &size));
    assert(!alloc_image(&ctx, UINT32_MAX, UINT32_MAX, 4, 16, 0, images));
}

static void closeDescriptor(VADRMPRIMESurfaceDescriptor *desc) {
    for (unsigned i = 0; i < desc->num_objects; i++) close(desc->objects[i].fd);
}

static void testDescriptor(void) {
    NVDriver drv = {0};
    FILE *a = tmpfile(), *b = tmpfile();
    assert(a != NULL && b != NULL);
    BackingImage img = {.format = NV_FORMAT_NV12, .fourcc = VA_FOURCC_NV12,
        .numObjects = 2, .numPlanes = 2, .fds = {fileno(a), fileno(b)},
        .objectSize = {8192, 16384}, .planeObjectIndex = {1, 0},
        .strides = {128, 128}, .mods = {DRM_FORMAT_MOD_LINEAR, DRM_FORMAT_MOD_LINEAR}};
    NVSurface surface = {.width = 128, .height = 128, .backingImage = &img};
    VADRMPRIMESurfaceDescriptor desc;
    assert(direct_fillExportDescriptor(&drv, &surface, &desc));
    assert(desc.num_objects == 2 && desc.layers[0].object_index[0] == 1 && desc.layers[1].object_index[0] == 0);
    assert(desc.objects[0].size == 8192 && desc.objects[1].size == 16384);
    struct stat original, exported;
    assert(fstat(fileno(b), &original) == 0 && fstat(desc.objects[1].fd, &exported) == 0);
    assert(original.st_ino == exported.st_ino && original.st_dev == exported.st_dev);
    assert(fcntl(desc.objects[0].fd, F_GETFD) & FD_CLOEXEC);
    closeDescriptor(&desc);
    img.numObjects = 1;
    img.planeObjectIndex[0] = 0;
    img.objectSize[0] = 24576;
    img.offsets[1] = 16384;
    assert(direct_fillExportDescriptor(&drv, &surface, &desc));
    assert(desc.num_objects == 1 && desc.layers[1].offset[0] == 16384);
    closeDescriptor(&desc);
    const uint32_t rgb[][2] = {
        {VA_FOURCC_ARGB, DRM_FORMAT_BGRA8888}, {VA_FOURCC_XRGB, DRM_FORMAT_BGRX8888},
        {VA_FOURCC_ABGR, DRM_FORMAT_RGBA8888}, {VA_FOURCC_XBGR, DRM_FORMAT_RGBX8888},
        {VA_FOURCC_RGBA, DRM_FORMAT_ABGR8888}, {VA_FOURCC_RGBX, DRM_FORMAT_XBGR8888},
        {VA_FOURCC_BGRA, DRM_FORMAT_ARGB8888}, {VA_FOURCC_BGRX, DRM_FORMAT_XRGB8888}};
    img.format = NV_FORMAT_ARGB;
    img.numPlanes = 1;
    for (unsigned i = 0; i < ARRAY_SIZE(rgb); i++) {
        img.fourcc = rgb[i][0];
        assert(direct_fillExportDescriptor(&drv, &surface, &desc));
        assert(desc.fourcc == rgb[i][0] && desc.layers[0].drm_format == rgb[i][1]);
        closeDescriptor(&desc);
    }
    img.objectSize[0] = UINT64_C(1) << 32;
    assert(!direct_fillExportDescriptor(&drv, &surface, &desc));
    assert(desc.num_objects == 0);
    fclose(a);
    fclose(b);
}

static void testCopyFailures(void) {
    CudaFunctions cuda = {.cuMemcpy2DAsync = mockCopy, .cuStreamSynchronize = mockSync,
        .cuEventRecord = mockEvent, .cuMemsetD8Async = mockMemset};
    NVDriver drv = {.cu = &cuda};
    BackingImage img = {.format = NV_FORMAT_NV12, .width = 4096, .height = 4096};
    NVSurface surface = {.width = 128, .height = 128, .backingImage = &img};
    for (unsigned scenario = 0; scenario < 5; scenario++) {
        copies = syncs = events = 0;
        copyFailure = scenario == 1 ? 1 : scenario == 2 ? 2 : 0;
        eventFailure = scenario == 3;
        syncFailure = scenario == 4;
        atomic_store(&drv.cudaWorkUnsafe, false);
        assert(copyFrameToSurface(&drv, 1, &surface, 128, (CUstream)1, (CUevent)1) == (scenario == 0));
        assert(syncs == 1);
        assert(atomic_load(&drv.cudaWorkUnsafe) == (scenario == 4));
    }
    pthread_mutex_init(&drv.securityClearMutex, NULL);
    drv.securityClearStream = (CUstream)1;
    drv.securityClearBuffer = 1;
    drv.securityClearBufferSize = 8 * 1024 * 1024;
    copies = syncs = events = 0;
    copyFailure = 2;
    syncFailure = 0;
    atomic_store(&drv.cudaWorkUnsafe, false);
    assert(!clearBackingImagePlaneGpu(&drv, &img, 0));
    assert(copies == 2 && syncs == 1 && !atomic_load(&drv.cudaWorkUnsafe));
    copies = syncs = 0;
    syncFailure = 1;
    assert(!clearBackingImage(&drv, &img)); // No CPU fallback after failed drain.
    assert(atomic_load(&drv.cudaWorkUnsafe));
    // A quarantined image must not be freed, even on allocation cleanup.
    destroyBackingImage(&drv, &img);
    pthread_mutex_destroy(&drv.securityClearMutex);
}

static int pushFailure, unmaps, decoderDestroys;
static NVSurface *workerSurface;
static CUresult CUDAAPI mockPush(CUcontext context) {
    return pushFailure ? CUDA_ERROR_UNKNOWN : CUDA_SUCCESS;
}
static CUresult CUDAAPI mockPop(CUcontext *context) { return CUDA_SUCCESS; }
static CUresult CUDAAPI mockCreateStream(CUstream *stream, unsigned flags) {
    *stream = (CUstream)1;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockCreateEvent(CUevent *event, unsigned flags) {
    *event = (CUevent)1;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockDestroyStream(CUstream stream) {
    assert(syncs > 0);
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockDestroyEvent(CUevent event) { return CUDA_SUCCESS; }
static CUresult CUDAAPI mockMap(CUvideodecoder decoder, int picture,
                                CUdeviceptr *ptr, unsigned *pitch, CUVIDPROCPARAMS *params) {
    *ptr = 1;
    *pitch = 128;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockUnmap(CUvideodecoder decoder, CUdeviceptr ptr) {
    assert(syncs > 0 && !syncFailure && workerSurface->resolving);
    assert(workerSurface->backingImage->resolving);
    unmaps++;
    return CUDA_SUCCESS;
}
static CUresult CUDAAPI mockDestroyDecoder(CUvideodecoder decoder) {
    assert(syncs > 0 && !syncFailure);
    decoderDestroys++;
    return CUDA_SUCCESS;
}

static void testWorkerFailures(void) {
    CudaFunctions cuda = {.cuMemcpy2DAsync = mockCopy, .cuStreamSynchronize = mockSync,
        .cuEventRecord = mockEvent, .cuCtxPushCurrent = mockPush, .cuCtxPopCurrent = mockPop,
        .cuStreamCreate = mockCreateStream, .cuEventCreate = mockCreateEvent,
        .cuStreamDestroy = mockDestroyStream, .cuEventDestroy = mockDestroyEvent};
    CuvidFunctions cuvid = {.cuvidMapVideoFrame = mockMap,
        .cuvidUnmapVideoFrame = mockUnmap, .cuvidDestroyDecoder = mockDestroyDecoder};
    cu = &cuda;
    cv = &cuvid;
    for (unsigned scenario = 0; scenario < 5; scenario++) {
        copies = syncs = events = unmaps = decoderDestroys = 0;
        copyFailure = scenario == 1 ? 2 : 0;
        eventFailure = scenario == 2;
        syncFailure = scenario == 3;
        pushFailure = scenario == 4;
        NVDriver drv = {.cu = &cuda, .backend = &DIRECT_BACKEND};
        BackingImage img = {.format = NV_FORMAT_NV12};
        assert(initBackingImageSync(&img));
        NVSurface surface = {.width = 128, .height = 128, .backingImage = &img,
            .resolving = 1, .submittedGeneration = 1};
        pthread_mutex_init(&surface.mutex, NULL);
        pthread_cond_init(&surface.cond, NULL);
        workerSurface = &surface;
        NVContext ctx = {.drv = &drv, .decoder = (CUvideodecoder)1};
        assert(resolveQueueInit(&ctx.resolveQueue));
        ResolveJob *job = calloc(1, sizeof(*job));
        assert(job != NULL);
        job->surface = &surface;
        job->decoder = ctx.decoder;
        job->generation = 1;
        assert(resolveQueuePush(&ctx.resolveQueue, job));
        resolveQueueShutdown(&ctx.resolveQueue);
        resolveSurfaces(&ctx);
        assert(!surface.resolving && !img.resolving);
        assert(surface.decodeFailed == (scenario != 0));
        assert(unmaps == (scenario < 3 ? 1 : 0));
        assert(decoderDestroys == (scenario < 3 ? 1 : 0));
        assert(atomic_load(&drv.cudaWorkUnsafe) == (scenario == 3));
        resolveQueueDestroy(&ctx.resolveQueue);
        pthread_cond_destroy(&surface.cond);
        pthread_mutex_destroy(&surface.mutex);
        pthread_cond_destroy(&img.cond);
        pthread_mutex_destroy(&img.mutex);
    }
    cu = NULL;
    cv = NULL;
}

int main(void) {
    testUuid();
    testGpuIdentity();
    testLayout();
    testDescriptor();
    testCopyFailures();
    testWorkerFailures();
#if NVD_TEST_VP9
    testVp9();
#endif
    return 0;
}
